author:
  name: Lisa Swid
  email: lr.swid@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4460292325820774
  brandStrength: 0.4765958
  lightness: 0.6435057166963816
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  rhythmicContrast: 0.8167483685538173
typography_spectrum: 0.7872341
layout_spectrum: 0.9319149
name: Swid Family Daycare
