color:
  brandColors:
    - '#909591'
    - '#24201F'
    - '#614F45'
    - '#7A7C64'
    - '#9EACAC'
  brandStrength: 0.476595
  lightness: 0.506578
  rhythmicContrast: 0.502192
  saturation: 0.498903
layout_spectrum: 0.561403
name: Swid Family Daycare
typography_spectrum: 0.7872341
