author:
  name: Lisa Swid
  email: lr.swid@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7872341
color:
  saturation: 0.5765957
  brandStrength: 0.4765958
  rhythmicContrast: 0.2553191
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  lightness: 0.6957447
layout_spectrum: 1
name: Swid Family Daycare
