name: Swid Family Daycare
layout_spectrum: 0.561403
typography_spectrum: 0.7872341
analytics:
  google: UA-78475073-2
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#D2BEA4'
    - '#41343E'
    - '#A48775'
    - '#675663'
    - '#946466'
  brandStrength: 0.5404255
  lightness: 0.506578
  saturation: 0.498903
  rhythmicContrast: 0.502192
title: ''
author:
  name: Lisa Swid
  url: ''
  email: ''
content_rating:
  adult: false
