color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.4765958
  lightness: 0.6957447
  rhythmicContrast: 0.2553191
  saturation: 0.5765957
layout_spectrum: 0.997807
name: Swid Family Daycare
typography_spectrum: 0.7872341
