author:
  name: Lisa Swid
  email: lr.swid@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.7872341
color:
  rhythmicContrast: 0.8167483685538173
  brandStrength: 0.9286011371295899
  saturation: 0.4460292325820774
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  lightness: 0.6435057166963816
layout_spectrum: 0.8508416349068284
name: Swid Family Daycare
