color:
  brandColors:
    - '#909591'
    - '#24201F'
    - '#614F45'
    - '#7A7C64'
    - '#9EACAC'
  brandStrength: 0.4765958
  lightness: 0.6957447
  rhythmicContrast: 0.2553191
  saturation: 0.5765957
layout_spectrum: 0.997807
name: Swid Family Daycare
typography_spectrum: 0.7872341
